In [1]:
import networkx as nx
from model import Model

model = Model()

In [ ]:
print(model.alpha)

In [27]:
print(model.alpha[0,350]) # this corresponds to the edge going from node zero to node 350

-6.96347005769e-05


In [13]:
import numpy as np
prout = np.array([0,1,2,3])

In [39]:
np.ones((1,3)).T

array([[1.],
       [1.],
       [1.]])

In [51]:
np.ones((1,3)) @ np.ones((1,3)).T

array([[3.]])

In [42]:
(model.alpha[0:3,0].T).*(np.ones((1,3)).T)

SyntaxError: invalid syntax (<ipython-input-42-a781510039f2>, line 1)

In [19]:
prout[0:]

array([0, 1, 2, 3])

In [70]:
(m.alpha.T @ m.y).shape

(517,)

In [80]:
(model.y * (model.beta.T @ (model.y - 1))) / model.y 

array([5.43244561e-04, 0.00000000e+00, 1.35656340e-01, 5.14295763e-02,
       3.06223835e-02, 5.05326990e-04, 8.76711144e-05, 8.83902467e-05,
       6.72430575e-04, 1.09665885e-03, 0.00000000e+00, 2.82915171e-03,
       9.93965057e-08, 1.49212600e-03, 4.63680553e-04, 1.42430101e-02,
       3.02281817e-04, 1.44698399e-03, 9.59284502e-04, 2.19766746e-02,
       1.72668150e+00, 4.84880768e-03, 1.83384819e-03, 2.28351138e-03,
       0.00000000e+00, 1.22826925e-03, 0.00000000e+00, 2.26681532e-03,
       1.74633915e-03, 2.17783019e-03, 0.00000000e+00, 0.00000000e+00,
       6.43576366e-04, 1.62827614e-07, 3.46555916e-05, 8.93018048e-04,
       0.00000000e+00, 2.69176049e-03, 1.10249668e-01, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 7.17381288e-03, 3.72647341e-03,
       4.42317135e-03, 0.00000000e+00, 1.48620940e-05, 6.55364591e-03,
       9.58164103e-04, 0.00000000e+00, 1.03805320e-02, 0.00000000e+00,
       6.72600953e-04, 2.42386232e-02, 0.00000000e+00, 5.58413388e-04,
      

In [95]:
import math
def evolve(model, dt):
  # want to multiply all edges going to zero with y
  # those edges correspond to alpha[:,0]
  # therefor we can transpose alpha and multiply it with y
  sum_ = model.alpha.T @ (model.y - 1) + model.y * (model.beta.T @ model.y) - model.beta.T @ np.ones(len(model.y))
  print(sum_.shape)
  # model.y = math.exp( dt*sum_/model.y) * model.y
  return np.exp( dt*sum_/model.y) * model.y


In [ ]:
model.y

In [96]:
evolve(model, 1)

(517,)


array([9.85347539e-001, 6.37764021e-001, 4.37409365e-002, 6.31563730e-002,
       1.26577389e-001, 9.10713380e-001, 7.66342465e-001, 9.71391971e-001,
       8.52210143e-001, 3.19745612e-001, 4.15992589e-002, 1.95346539e-001,
       4.54347645e-001, 2.31686845e-001, 8.40346798e-001, 1.43982777e-001,
       7.01412353e-001, 1.71379535e-001, 9.07881645e-001, 3.68434137e-001,
       8.10625462e-003, 5.02511846e-001, 3.83210500e-001, 7.38410826e-001,
       2.23838848e-001, 9.62460588e-001, 9.13529642e-001, 6.48356218e-001,
       4.78213414e-001, 4.94910840e-001, 2.02311758e-001, 1.67058450e-001,
       3.78180279e-001, 8.10741046e-001, 3.06882168e-001, 4.13838889e-001,
       6.39077141e-001, 9.87907687e-001, 1.26732304e-001, 8.46514072e-001,
       7.42663200e-001, 6.49995974e-001, 4.00237357e-001, 9.28332085e-001,
       2.75406656e-001, 5.61741510e-001, 9.71629954e-001, 2.72487481e-001,
       9.17544271e-001, 1.40788064e-001, 4.20151628e-001, 2.61952824e-001,
       4.15498995e-001, 1

In [2]:
model.y

array([2.47103747e-01, 6.25886982e-01, 1.67501923e-02, 1.64452664e-01,
       5.14112570e-01, 2.44381004e-01, 2.87047702e-01, 7.61145230e-01,
       8.08191028e-01, 5.26406418e-01, 1.46690638e-01, 5.42292591e-01,
       5.06863705e-01, 5.27362171e-01, 4.45653808e-01, 6.02397259e-02,
       8.69474221e-01, 9.74347292e-02, 7.12434036e-01, 8.35896994e-02,
       8.92012545e-01, 7.57728846e-01, 4.99460562e-01, 5.29989569e-01,
       3.51705598e-01, 9.31276434e-01, 7.93305058e-01, 4.84754761e-01,
       8.99037693e-01, 4.61645452e-01, 3.12126113e-01, 5.83789065e-01,
       8.44879990e-01, 3.43974989e-01, 6.17770286e-01, 9.08852204e-01,
       6.99002695e-01, 2.01713669e-01, 6.90818103e-01, 2.79479703e-01,
       4.72904261e-01, 7.74782002e-01, 8.39179313e-01, 2.09283781e-02,
       1.43050515e-01, 3.02139781e-01, 4.11161258e-01, 6.59437526e-01,
       6.37491179e-01, 4.19809237e-02, 2.30448842e-01, 8.71346950e-01,
       6.82653771e-01, 9.45142045e-01, 8.72867161e-01, 6.15198764e-02,
      

In [4]:
import numpy as np
temp = np.copy(model.y)


model.evolve(10)



In [10]:
print(np.concatenate(temp.reshape(len(temp),1), model.y.reshape(len(model.y),1)))

TypeError: only integer scalar arrays can be converted to a scalar index

In [21]:
print(np.concatenate((temp.reshape(len(temp),1), model.y.reshape(len(model.y),1)), axis=1)[0:10,:])

[[2.47103747e-01 1.91614498e-01]
 [6.25886982e-01 6.25818722e-01]
 [1.67501923e-02 2.63872115e-07]
 [1.64452664e-01 1.67461561e-01]
 [5.14112570e-01 4.23537272e-01]
 [2.44381004e-01 2.42027538e-01]
 [2.87047702e-01 2.03280729e-01]
 [7.61145230e-01 7.58890647e-01]
 [8.08191028e-01 8.14943646e-01]
 [5.26406418e-01 4.77621314e-01]]
